import { expect, test, type Page } from '@playwright/test'

async function navigate(page: Page, label: string) {
  const menu = page.getByRole('button', { name: 'Open navigation' })
  if (await menu.isVisible()) await menu.click()
  await page.getByRole('link', { name: label, exact: true }).click()
}

test('cached-data demo: simulation, presets, risk, mechanics, research, search and assumptions', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const simulated = page.waitForResponse(response => response.url().endsWith('/api/simulations') && response.status() === 200)
  await page.goto('/')
  const result = await (await simulated).json()
  await expect(page.getByRole('heading', { name: 'Hedge simulator', exact: true })).toBeVisible()
  await expect(page.getByText('Results current', { exact: true })).toBeVisible()
  await expect(page.getByText('Cached market data', { exact: true })).toHaveCount(1)
  await expect(page.getByText('Synthetic data', { exact: true })).toHaveCount(0)
  await expect(page.locator('.plot-container')).toHaveCount(1)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `test-results/overview-${test.info().project.name}.png`, fullPage: true, animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBeTruthy()
  const usd = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })
  for (const row of result.summary) {
    await expect(page.getByRole('table')).toContainText(usd.format(row.final_pnl))
  }
  await page.getByLabel('Hedge ratio', { exact: true }).fill('0')
  await expect(page.getByText('Results current', { exact: true })).toBeVisible()
  const zero = await page.request.post('/api/simulations', { data: { book_size: 1_000_000, hedge_ratio: 0, annual_borrow_rate: .02,
    start_date: '2022-01-03', end_date: '2022-12-30' } })
  expect((await zero.json()).summary.every((row: { final_pnl: number }) => row.final_pnl === result.summary[0].final_pnl)).toBeTruthy()
  await page.getByLabel('Hedge ratio', { exact: true }).fill('0.6')
  await page.getByRole('radio', { name: '2020 stress', exact: true }).click()
  await expect(page.locator('.effective')).toContainText('2020')
  await page.getByRole('radio', { name: 'Choppy period', exact: true }).click()
  await expect(page.locator('.scenario-note')).toContainText('126-interval')
  await page.getByRole('radio', { name: '2022 drawdown', exact: true }).click()
  await expect(page.locator('.effective')).toContainText('2022')
  await navigate(page, 'Risk analysis')
  await expect(page.getByRole('table')).toContainText('-$11,868')
  await expect(page.locator('.plot-container')).toHaveCount(2)
  await navigate(page, 'Hedge mechanics')
  await expect(page.getByRole('heading', { name: 'Two-day illustration' })).toBeVisible()
  await expect(page.locator('.plot-container')).toHaveCount(1)
  await navigate(page, 'Research')
  await expect(page.getByRole('heading', { name: 'Daily sanity check', exact: true })).toBeVisible()
  await expect(page.locator('.plot-container')).toHaveCount(3)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `test-results/research-${test.info().project.name}.png`, fullPage: true, animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBeTruthy()
  await page.getByRole('radio', { name: '21d', exact: true }).click()
  await expect(page.getByText('Each window uses 21 return intervals', { exact: false })).toBeVisible()
  await navigate(page, 'Recommendation')
  await expect(page.getByRole('button', { name: /Use .* in simulator/ })).toBeVisible()
  await page.getByRole('radio', { name: 'Static short', exact: true }).click()
  await expect(page.locator('.rec-main')).toContainText('Static short')
  await page.getByRole('button', { name: /Use .* in simulator/ }).click()
  await expect(page.getByRole('heading', { name: 'Hedge simulator', exact: true })).toBeVisible()
  await navigate(page, 'Assumptions')
  await expect(page.getByText('HTTP API', { exact: true })).toBeVisible()
  await expect(page.getByText(/original retrieval time and provider response were not recorded/)).toBeVisible()
  await expect(page.getByText('No spreads', { exact: false })).toBeVisible()
  expect(errors).toEqual([])
  await page.evaluate(() => window.scrollTo(0, 0))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBeTruthy()
  await page.screenshot({ path: `test-results/demo-${test.info().project.name}.png`, fullPage: true, animations: 'disabled' })
  await page.screenshot({ path: `test-results/viewport-${test.info().project.name}.png`, animations: 'disabled' })
})

test('invalid inputs retain useful errors and a corrected request recovers', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('Results current', { exact: true })).toBeVisible()
  await page.getByLabel('Hedge ratio', { exact: true }).fill('2')
  await expect(page.getByText('Hedge ratio must be between 0 and 1.', { exact: true })).toBeVisible()
  await expect(page.getByText('Inputs need attention', { exact: true })).toBeVisible()
  await page.getByLabel('Hedge ratio', { exact: true }).fill('0.5')
  await expect(page.getByText('Results current', { exact: true })).toBeVisible()
  await expect(page.getByText('Chart failed to load.', { exact: true })).toHaveCount(0)
})
